import 'dotenv/config';
import fs from 'node:fs';
import { Client, PermissionsBitField, SlashCommandBuilder, EmbedBuilder } from 'discord.js';
import OpenAI from 'openai';
import gifFrames from 'gif-frames';
import sharp from 'sharp';

const openai = process.env.OPENAI_API_KEY ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY, maxRetries: 0 }) : null;
const DATA_FILE = './settings.json';
const DEFAULTS = { prefix: "'", nsfwFilter: true, goreFilter: true, piiFilter: true, auditChannelId: null, antiInvite: true, antiSpam: true, warnings: {}, channelModes: {}, history: {} };
const cache = new Map(), userRate = new Map(), spam = new Map(), mentionSpam = new Map(), imageSpam = new Map(), repeatedSpam = new Map(), activeSpam = new Map(), automodRules = new Map(), historyRuntime = new Map(), dashboard = new Map(), queue = [];
let active = 0;
const MAX_CONCURRENCY=1, USER_WINDOW=10000, USER_LIMIT=8, FLOOD_WINDOW=10000, FLOOD_LIMIT=15, MENTION_WINDOW=8000, MENTION_LIMIT=6, IMAGE_WINDOW=10000, IMAGE_LIMIT=6, MAX_QUEUE=100;
const IMAGE_TYPES=new Set(['image/jpeg','image/jpg','image/png','image/webp','image/gif']);
const GIF_FRAME_LIMIT=8, GIF_MAX_BYTES=15*1024*1024, REPEAT_WINDOW=15000, REPEAT_LIMIT=3, SIMILARITY_THRESHOLD=0.88, ACTIVE_SPAM_COOLDOWN=7000, MAX_HISTORY=100;
function load(){try{return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));}catch{return {};}}
const data=load();
function save(){try{fs.writeFileSync(DATA_FILE,JSON.stringify(data,null,2));}catch(e){console.error('[mod] settings save failed:',e.message);}}
function cfg(gid){if(!data[gid])data[gid]=structuredClone(DEFAULTS);data[gid]={...DEFAULTS,...data[gid],warnings:data[gid].warnings||{},channelModes:data[gid].channelModes||{},history:data[gid].history||{}};return data[gid];}
function channelMode(gid,cid){return cfg(gid).channelModes?.[cid]||'normal';}
function addHistory(gid,uid,item){const c=cfg(gid),a=c.history[uid]||[];a.push({...item,at:item.at||new Date().toISOString()});c.history[uid]=a.slice(-MAX_HISTORY);save();}
function addEvent(gid,cid,type){const d=dashboard.get(gid)||{};d.byType=d.byType||{};d.byType[type]=(d.byType[type]||0)+1;d.byChannel=d.byChannel||{};d.byChannel[cid]=(d.byChannel[cid]||0)+1;dashboard.set(gid,d);}
function mod(member){return !!(member?.permissions.has(PermissionsBitField.Flags.ManageGuild)||member?.permissions.has(PermissionsBitField.Flags.ManageMessages)||member?.permissions.has(PermissionsBitField.Flags.Administrator));}
function norm(s=''){return s.normalize('NFKC').toLowerCase().replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/[@4]/g,'a').replace(/3/g,'e').replace(/[1!]/g,'i').replace(/0/g,'o').replace(/5/g,'s').replace(/7/g,'t').replace(/\s+/g,' ').trim();}
function redact(s=''){return s.replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'[email redacted]').replace(/\b(?:https?:\/\/)?(?:\d{1,3}\.){3}\d{1,3}\b/g,'[IP redacted]').replace(/\b(?:\d{1,5}\s+)?[A-Za-z0-9.'-]+\s+(?:street|st|road|rd|avenue|ave|lane|ln|drive|dr|close|court|ct|way|boulevard|blvd)\b[^,\n]{0,80}/gi,'[address redacted]');}
function preview(s=''){return redact(s).slice(0,700).replace(/`/g,'ˋ');}
function attachmentSummary(attachments=[]){return attachments.length?attachments.slice(0,8).map(a=>`\`${a.name||'attachment'}\` (${a.contentType||'unknown'})`).join(', '):'[none]';}
async function log(g,title,body,color=0x5865f2){const c=cfg(g.id);if(!c.auditChannelId)return;const ch=g.channels.cache.get(c.auditChannelId);if(!ch?.isTextBased())return;await ch.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(body.slice(0,3900)).setColor(color).setTimestamp()]}).catch(()=>{});}
function cached(k){const x=cache.get(k);if(!x||Date.now()-x.time>30000){cache.delete(k);return null;}return x.result;}
function put(k,result){cache.set(k,{result,time:Date.now()});if(cache.size>500)cache.delete(cache.keys().next().value);}
async function api(fn){for(let i=0;i<3;i++){try{return await fn();}catch(e){if(e?.status!==429)throw e;await new Promise(r=>setTimeout(r,Math.min(8000,1000*(i+1))));}}throw new Error('moderation API rate limited');}
function enqueue(fn){if(queue.length>=MAX_QUEUE)queue.shift();queue.push(fn);runQueue();}
async function runQueue(){if(active>=MAX_CONCURRENCY||!queue.length)return;active++;const fn=queue.shift();try{await fn();}catch(e){console.error('[mod] task failed:',e?.message||e);}finally{active--;runQueue();}}
function reasons(result,c){const x=result?.categories||{},s=result?.category_scores||{},r=[];if(c.nsfwFilter&&(x.sexual||x['sexual/minors']||s.sexual>=0.85||s['sexual/minors']>=0.20))r.push('NSFW/sexual content');if(c.goreFilter&&(x['violence/graphic']||s['violence/graphic']>=0.78))r.push('graphic violence/gore');return r;}
function extractGifUrls(text=''){const urls=[];const re=/https?:\/\/[^\s<>]+/gi;for(const raw of text.match(re)||[]){const url=raw.replace(/[)>\]}>,.!?]+$/,'');if(/\.gif(?:\?[^\s]*)?$/i.test(url)||/\b(?:tenor\.com|giphy\.com)\b/i.test(url))urls.push(url);}return [...new Set(urls)].slice(0,4);}
async function fetchBuffer(url){const res=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Discord-Moderation-Bot/1.0'}});if(!res.ok)throw new Error(`GIF download failed: HTTP ${res.status}`);const len=Number(res.headers.get('content-length')||0);if(len>GIF_MAX_BYTES)throw new Error('GIF exceeds size limit');const buf=Buffer.from(await res.arrayBuffer());if(buf.length>GIF_MAX_BYTES)throw new Error('GIF exceeds size limit');return buf;}
async function analyzeGifFrames(url,c){if(!openai||!url)return [];const key=`gif:${url.split('?')[0]}`;const hit=cached(key);if(hit)return reasons(hit,c);try{const buf=await fetchBuffer(url);const frames=await gifFrames({url:buf,frames:'all',outputType:'png',cumulative:true});if(!frames?.length)return [];const indexes=[...new Set([0,Math.floor((frames.length-1)*.14),Math.floor((frames.length-1)*.29),Math.floor((frames.length-1)*.43),Math.floor((frames.length-1)*.57),Math.floor((frames.length-1)*.71),Math.floor((frames.length-1)*.86),frames.length-1])].slice(0,GIF_FRAME_LIMIT);const selected=indexes.map(i=>frames[i]);const inputs=[];for(const frame of selected){const png=frame.getImage();const resized=await sharp(png).resize({width:640,height:640,fit:'inside',withoutEnlargement:true}).png().toBuffer();inputs.push({type:'image_url',image_url:{url:`data:image/png;base64,${resized.toString('base64')}`}});}const r=await api(()=>openai.moderations.create({model:'omni-moderation-latest',input:inputs}));const result=r.results?.find(x=>reasons(x,c).length)||r.results?.[0];put(key,result||{});return reasons(result,c);}catch(e){console.error('[mod] GIF frame analysis:',e?.message||e);return [];}}
async function combinedModeration(text,attachments,c){if(!openai||(!c.nsfwFilter&&!c.goreFilter))return [];const images=attachments.filter(a=>a.contentType&&IMAGE_TYPES.has(a.contentType)&&a.contentType!=='image/gif').slice(0,8);const gifs=attachments.filter(a=>a.contentType==='image/gif'||/\.gif(?:\?|$)/i.test(a.url));const gifUrls=extractGifUrls(text);const key=`mod:${norm(text)}|${images.map(a=>a.url.split('?')[0]).join('|')}`;const hit=cached(key);if(hit)return reasons(hit,c);const input=[];if(text)input.push({type:'text',text:text.slice(0,4000)});for(const a of images)input.push({type:'image_url',image_url:{url:a.url}});if(input.length){const r=await api(()=>openai.moderations.create({model:'omni-moderation-latest',input}));const result=r.results?.[0];if(reasons(result,c).length)return reasons(result,c);put(key,result);}
for(const a of gifs){const rr=await analyzeGifFrames(a.url,c);if(rr.length)return rr;}for(const url of gifUrls){if(!gifs.some(a=>a.url.split('?')[0]===url.split('?')[0])){const rr=await analyzeGifFrames(url,c);if(rr.length)return rr;}}return [];}
async function aiContextCheck(text,c){if(!openai||!text||text.length<3||(!c.nsfwFilter&&!c.goreFilter))return [];const key=`ctx:${norm(text)}`;const hit=cached(key);if(hit!==null)return Array.isArray(hit)?hit:[];try{const r=await api(()=>openai.responses.create({model:'gpt-5.6-luna',input:[{role:'system',content:'You are a strict Discord safety classifier. Return only JSON with nsfw and gore booleans. Classify the meaning and context of the text, not isolated words. nsfw=true only for sexually explicit or strongly sexual content; gore=true only for graphic descriptions of severe injury, mutilation, dismemberment, or explicit bloody violence. Do not flag ordinary profanity, insults, harmless numbers, news/history discussion, medical/educational discussion, game/movie references without graphic detail, or non-graphic fictional references.'},{role:'user',content:text.slice(0,2500)}],text:{format:{type:'json_schema',name:'safety',strict:true,schema:{type:'object',properties:{nsfw:{type:'boolean'},gore:{type:'boolean'}},required:['nsfw','gore'],additionalProperties:false}}}}));const result=JSON.parse(r.output_text||'{"nsfw":false,"gore":false}');const reasons=[];if(c.nsfwFilter&&result.nsfw)reasons.push('NSFW/sexual content');if(c.goreFilter&&result.gore)reasons.push('graphic violence/gore');put(key,reasons);return reasons;}catch{return [];}}
async function contentScan(message){if(!message.guild)return;const c=cfg(message.guild.id);const text=message.content?.trim()||'';const attachments=[...message.attachments.values()];try{const r=await combinedModeration(text,attachments,c);let reasonsFound=r;if(!reasonsFound.length&&text.length>=3)reasonsFound=await aiContextCheck(text,c);if(reasonsFound.length){await message.delete().catch(()=>{});const d=dashboard.get(message.guild.id)||{};d.removed=(d.removed||0)+1;dashboard.set(message.guild.id,d);await log(message.guild,'🛡️ Content deleted',`${message.author} • **Channel:** <#${message.channel.id}>\n**Message ID:** \`${message.id}\`\n**Reason:** ${reasonsFound.join(' + ')}\n**Attachments:** ${attachmentSummary(attachments)}\n**Message:** ${preview(text)||'[attachment/GIF]'}`,0xed4245);return;}if(c.piiFilter&&text){const red=redact(text);if(red!==text){await message.edit(red.slice(0,2000)).catch(()=>{});const d=dashboard.get(message.guild.id)||{};d.pii=(d.pii||0)+1;dashboard.set(message.guild.id,d);await log(message.guild,'🔒 PII redacted',`${message.author} • **Channel:** <#${message.channel.id}>\n**Message ID:** \`${message.id}\`\n**Message:** ${preview(red)}`);}}}catch(e){console.error('[mod] content scan:',e?.message||e);}}
function rateLimited(gid,uid){const key=`${gid}:${uid}`,now=Date.now(),x=userRate.get(key)||[];while(x.length&&now-x[0]>USER_WINDOW)x.shift();if(x.length>=USER_LIMIT){userRate.set(key,x);return true;}x.push(now);userRate.set(key,x);return false;}
async function imageSpamScan(message){
  const c=cfg(message.guild.id);
  if(!c.antiSpam)return;
  const imageCount=[...message.attachments.values()].filter(a=>IMAGE_TYPES.has(a.contentType)||/\\.(?:png|jpe?g|webp|gif)(?:\\?|$)/i.test(a.url||'')).length;
  if(!imageCount)return;
  const key=`${message.guild.id}:${message.author.id}`,now=Date.now();
  const x=imageSpam.get(key)||[];
  x.push({message,count:imageCount,time:now});
  while(x.length&&now-x[0].time>IMAGE_WINDOW)x.shift();
  imageSpam.set(key,x);
  const total=x.reduce((sum,v)=>sum+v.count,0);
  if(total<IMAGE_LIMIT)return;
  let deleted=0;
  for(const v of x){
    if(await v.message.delete().then(()=>true).catch(()=>false))deleted++;
  }
  imageSpam.delete(key);
  const d=dashboard.get(message.guild.id)||{};
  d.imageSpam=(d.imageSpam||0)+1;
  dashboard.set(message.guild.id,d);
  await log(message.guild,'🖼️ Image spam blocked',`${message.author} • **Channel:** <#${message.channel.id}>\\n**Messages deleted:** ${deleted}\\n**Images removed:** ${total}\\n**Trigger:** ${IMAGE_LIMIT}+ images within ${IMAGE_WINDOW/1000}s`,0xed4245);
}
function spamFingerprint(text=''){return norm(text).replace(/[^a-z0-9\s]/g,'').replace(/\s+/g,' ').trim();}\nfunction similarity(a,b){if(!a||!b)return 0;if(a===b)return 1;const ta=new Set(a.split(' ').filter(Boolean)),tb=new Set(b.split(' ').filter(Boolean));if(!ta.size||!tb.size)return 0;let same=0;for(const t of ta)if(tb.has(t))same++;return same/(ta.size+tb.size-same);}\nasync function getAutoModRules(guild){const hit=automodRules.get(guild.id);if(hit&&Date.now()-hit.time<60000)return hit.rules;try{const rules=await guild.autoModerationRules.fetch();const list=[...rules.values()].filter(r=>r.enabled);automodRules.set(guild.id,{rules:list,time:Date.now()});return list;}catch{return [];}}
function automodMatches(message){if(!message.content)return Promise.resolve([]);return getAutoModRules(message.guild).then(rules=>{const n=norm(message.content),compactText=n.replace(/[^a-z0-9]/g,''),out=[];for(const rule of rules){const md=rule.triggerMetadata||{};for(const kw of md.keywordFilter||[]){const target=norm(String(kw).replace(/\*/g,''));if(target.length>=3&&(n.includes(target)||compactText.includes(target.replace(/[^a-z0-9]/g,''))))out.push(rule.name+': '+kw);}for(const pattern of md.regexPatterns||[]){try{const re=new RegExp(pattern,'iu');if(re.test(message.content)||re.test(n))out.push(rule.name+': regex');}catch{}}}return [...new Set(out)].slice(0,5);});}
async function repeatedContentScan(message){const c=cfg(message.guild.id);if(!c.antiSpam||mod(message.member)||channelMode(message.guild.id,message.channel.id)==='off')return false;const fp=spamFingerprint(message.content||'');if(fp.length<8)return false;const key=message.guild.id+':'+message.author.id,now=Date.now();const x=repeatedSpam.get(key)||[];while(x.length&&now-x[0].time>REPEAT_WINDOW)x.shift();const match=x.find(v=>similarity(fp,v.fp)>=SIMILARITY_THRESHOLD);x.push({message,fp,time:now});repeatedSpam.set(key,x.slice(-8));if(!match)return false;const recent=x.slice(-REPEAT_LIMIT);if(recent.length<REPEAT_LIMIT)return false;let deleted=0;for(const v of recent)if(await v.message.delete().then(()=>true).catch(()=>false))deleted++;repeatedSpam.delete(key);activeSpam.set(key,{fps:[fp,match.fp],until:Date.now()+ACTIVE_SPAM_COOLDOWN});addHistory(message.guild.id,message.author.id,{type:'Repeated spam',channelId:message.channel.id,messageId:message.id,details:{reason:'Repeated or near-identical content',messagesDeleted:deleted}});addEvent(message.guild.id,message.channel.id,'Repeated spam');const d=dashboard.get(message.guild.id)||{};d.spam=(d.spam||0)+1;dashboard.set(message.guild.id,d);await log(message.guild,'📋 Repeated spam blocked',message.author+' • **Channel:** <#'+message.channel.id+'>\n**Messages deleted:** '+deleted+'\n**State:** active for '+ACTIVE_SPAM_COOLDOWN/1000+'s',0xed4245);return true;}
async function spamScan(message){const c=cfg(message.guild.id);if(!c.antiSpam||mod(message.member))return;if(await repeatedContentScan(message))return;if(rateLimited(message.guild.id,message.author.id))return;const key=`${message.guild.id}:${message.author.id}`,now=Date.now();const x=spam.get(key)||[];x.push(message);while(x.length&&now-x[0].createdTimestamp>FLOOD_WINDOW)x.shift();spam.set(key,x);const mentions=message.mentions.users.size+message.mentions.roles.size+(message.mentions.everyone?5:0);const m=mentionSpam.get(key)||[];m.push({message,n:mentions,time:now});while(m.length&&now-m[0].time>MENTION_WINDOW)m.shift();mentionSpam.set(key,m);const mentionTotal=m.reduce((a,b)=>a+b.n,0);if(mentionTotal>=MENTION_LIMIT){for(const v of m)await v.message.delete().catch(()=>{});mentionSpam.delete(key);const d=dashboard.get(message.guild.id)||{};d.spam=(d.spam||0)+1;dashboard.set(message.guild.id,d);await log(message.guild,'🚨 Mention spam blocked',`${message.author} • **Channel:** <#${message.channel.id}>\n**Mentions removed:** ${mentionTotal}\n**Trigger:** ${MENTION_LIMIT}+ mentions within ${MENTION_WINDOW/1000}s`,0xed4245);return;}if(x.length>=FLOOD_LIMIT){const targets=x.slice(-30);let deleted=0;for(const m of targets)if(await m.delete().then(()=>true).catch(()=>false))deleted++;spam.delete(key);const d=dashboard.get(message.guild.id)||{};d.spam=(d.spam||0)+1;dashboard.set(message.guild.id,d);await log(message.guild,'🌊 Flood blocked',`${message.author} • **Channel:** <#${message.channel.id}>\n**Messages deleted:** ${deleted}\n**Trigger:** ${FLOOD_LIMIT}+ messages within ${FLOOD_WINDOW/1000}s`,0xed4245);}}
function panelEmbed(gid){const c=cfg(gid),d=dashboard.get(gid)||{};return new EmbedBuilder().setTitle('🛡️ Moderation dashboard').setColor(0x5865f2).addFields({name:'Prefix',value:`\`${c.prefix}\``,inline:true},{name:'NSFW',value:c.nsfwFilter?'🟢 On':'🔴 Off',inline:true},{name:'Gore',value:c.goreFilter?'🟢 On':'🔴 Off',inline:true},{name:'PII',value:c.piiFilter?'🟢 On':'🔴 Off',inline:true},{name:'Anti-spam/flood',value:c.antiSpam?'🟢 On':'🔴 Off',inline:true},{name:'Scans',value:String(d.scans||0),inline:true},{name:'Removed',value:String(d.removed||0),inline:true},{name:'Spam events',value:String(d.spam||0),inline:true},{name:'Image spam',value:String(d.imageSpam||0),inline:true},{name:'PII redactions',value:String(d.pii||0),inline:true});}
function install(client){if(client.__advancedModerationInstalled)return;client.__advancedModerationInstalled=true;client.on('messageCreate',m=>{if(!m.inGuild()||m.author.bot)return;const d=dashboard.get(m.guild.id)||{};d.scans=(d.scans||0)+1;dashboard.set(m.guild.id,d);spamScan(m);imageSpamScan(m);enqueue(()=>contentScan(m));});client.on('messageUpdate',async(oldM,newM)=>{if(!newM.inGuild()||newM.author?.bot)return;await newM.fetch().catch(()=>{});enqueue(()=>contentScan(newM));});client.on('ready',async()=>{setTimeout(async()=>{try{const existing=await client.application.commands.fetch();const extras=[new SlashCommandBuilder().setName('modpanel').setDescription('Open the moderation dashboard'),new SlashCommandBuilder().setName('modstats').setDescription('Show moderation statistics'),new SlashCommandBuilder().setName('prefix').setDescription('Change the server prefix').addStringOption(o=>o.setName('value').setDescription('1-3 characters').setRequired(true))];for(const command of extras){const json=command.toJSON();if(!existing.some(x=>x.name===json.name))await client.application.commands.create(json);}}catch(e){console.error('[mod] dashboard command registration:',e.message);}},1500);});client.on('interactionCreate',async i=>{if(!i.isChatInputCommand()||!i.inGuild())return;if(i.commandName==='modpanel'||i.commandName==='modstats'){if(!mod(i.member))return i.reply({content:'❌ Moderator permission required.',ephemeral:true});return i.reply({embeds:[panelEmbed(i.guild.id)],ephemeral:true});}});}
const OriginalLogin=Client.prototype.login;Client.prototype.login=async function(...args){install(this);return OriginalLogin.apply(this,args);};
