import 'dotenv/config';
import fs from 'node:fs';
import { Client, PermissionsBitField, SlashCommandBuilder, EmbedBuilder } from 'discord.js';
import OpenAI from 'openai';

const openai = process.env.OPENAI_API_KEY ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY, maxRetries: 0 }) : null;
const DATA_FILE = './settings.json';
const DEFAULTS = { prefix: "'", nsfwFilter: true, goreFilter: true, piiFilter: true, auditChannelId: null, antiInvite: true, antiSpam: true, warnings: {} };
const cache = new Map(), userRate = new Map(), spam = new Map(), mentionSpam = new Map(), dashboard = new Map(), queue = [];
let active = 0;
const MAX_CONCURRENCY=1, USER_WINDOW=10000, USER_LIMIT=8, FLOOD_WINDOW=10000, FLOOD_LIMIT=15, MENTION_WINDOW=8000, MENTION_LIMIT=6, MAX_QUEUE=100;
const IMAGE_TYPES=new Set(['image/jpeg','image/jpg','image/png','image/webp','image/gif']);
function load(){try{return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));}catch{return {};}}
const data=load();
function save(){try{fs.writeFileSync(DATA_FILE,JSON.stringify(data,null,2));}catch(e){console.error('[mod] settings save failed:',e.message);}}
function cfg(gid){if(!data[gid])data[gid]=structuredClone(DEFAULTS);data[gid]={...DEFAULTS,...data[gid],warnings:data[gid].warnings||{}};return data[gid];}
function mod(member){return !!(member?.permissions.has(PermissionsBitField.Flags.ManageGuild)||member?.permissions.has(PermissionsBitField.Flags.ManageMessages)||member?.permissions.has(PermissionsBitField.Flags.Administrator));}
function norm(s=''){return s.normalize('NFKC').toLowerCase().replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/[@4]/g,'a').replace(/3/g,'e').replace(/[1!]/g,'i').replace(/0/g,'o').replace(/5/g,'s').replace(/7/g,'t').replace(/\s+/g,' ').trim();}
function redact(s=''){return s.replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'[email redacted]').replace(/\b(?:https?:\/\/)?(?:\d{1,3}\.){3}\d{1,3}\b/g,'[IP redacted]').replace(/\b(?:\d{1,5}\s+)?[A-Za-z0-9.'-]+\s+(?:street|st|road|rd|avenue|ave|lane|ln|drive|dr|close|court|ct|way|boulevard|blvd)\b[^,\n]{0,80}/gi,'[address redacted]');}
function preview(s=''){return redact(s).slice(0,700).replace(/`/g,'ˋ');}
async function log(g,title,body,color=0x5865f2){const c=cfg(g.id);if(!c.auditChannelId)return;const ch=g.channels.cache.get(c.auditChannelId);if(!ch?.isTextBased())return;await ch.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(body.slice(0,3900)).setColor(color).setTimestamp()]}).catch(()=>{});}
function cached(k){const x=cache.get(k);if(!x||Date.now()-x.time>30000){cache.delete(k);return null;}return x.result;}
function put(k,result){cache.set(k,{result,time:Date.now()});if(cache.size>500)cache.delete(cache.keys().next().value);}
async function api(fn){for(let i=0;i<3;i++){try{return await fn();}catch(e){if(e?.status!==429)throw e;await new Promise(r=>setTimeout(r,Math.min(8000,1000*(i+1))));}}throw new Error('moderation API rate limited');}
function enqueue(fn){if(queue.length>=MAX_QUEUE)queue.shift();queue.push(fn);runQueue();}
async function runQueue(){if(active>=MAX_CONCURRENCY||!queue.length)return;active++;const fn=queue.shift();try{await fn();}catch(e){console.error('[mod] task failed:',e?.message||e);}finally{active--;runQueue();}}
function reasons(result,c){const x=result?.categories||{},r=[];if(c.nsfwFilter&&(x.sexual||x['sexual/minors']))r.push('NSFW/sexual content');if(c.goreFilter&&x['violence/graphic'])r.push('graphic violence/gore');return r;}
async function combinedModeration(text,attachments,c){if(!openai||(!c.nsfwFilter&&!c.goreFilter))return [];const images=attachments.filter(a=>a.contentType&&IMAGE_TYPES.has(a.contentType));const key=`mod:${norm(text)}|${images.map(a=>a.url.split('?')[0]).join('|')}`;const hit=cached(key);if(hit)return reasons(hit,c);const input=[];if(text)input.push({type:'text',text:text.slice(0,4000)});for(const a of images)input.push({type:'image_url',image_url:{url:a.url}});if(!input.length)return [];const r=await api(()=>openai.moderations.create({model:'omni-moderation-latest',input}));const result=r.results?.[0];put(key,result);return reasons(result,c);}
async function aiContextCheck(text){
  if(!openai||!text||text.length<3)return false;
  const key=`ctx:${norm(text)}`;
  const hit=cached(key);
  if(hit!==null)return !!hit;
  try{
    const r=await api(()=>openai.responses.create({
      model:'gpt-5.6-luna',
      input:[
        {role:'system',content:'You are a Discord safety classifier. Return only JSON: {"unsafe":true|false}. Judge the meaning and context of the text for graphic violence/gore or sexual/NSFW content. Do not flag ordinary profanity, harmless numbers, news/history discussion, or non-graphic fictional references.'},
        {role:'user',content:text.slice(0,2500)}
      ],
      text:{format:{type:'json_schema',name:'safety',strict:true,schema:{type:'object',properties:{unsafe:{type:'boolean'}},required:['unsafe'],additionalProperties:false}}}
    }));
    const result=JSON.parse(r.output_text||'{"unsafe":false}');
    put(key,result.unsafe);
    return !!result.unsafe;
  }catch{return false;}
}
async function contentScan(message){if(!message.guild)return;const c=cfg(message.guild.id);const text=message.content?.trim()||'';const attachments=[...message.attachments.values()];try{const r=await combinedModeration(text,attachments,c);let unsafe=r.length>0;if(!unsafe&&text.length>=3)unsafe=await aiContextCheck(text);if(unsafe){await message.delete().catch(()=>{});const d=dashboard.get(message.guild.id)||{};d.removed=(d.removed||0)+1;dashboard.set(message.guild.id,d);await log(message.guild,'🛡️ AI content moderation',`${message.author} • **Channel:** <#${message.channel.id}>\n**Message ID:** \`${message.id}\`\n**Reason:** ${r.join(' + ')||'AI context classifier'}\n**Message:** ${preview(text)||'[attachment]'}`,0xed4245);return;}if(c.piiFilter&&text){const red=redact(text);if(red!==text){await message.edit(red.slice(0,2000)).catch(()=>{});const d=dashboard.get(message.guild.id)||{};d.pii=(d.pii||0)+1;dashboard.set(message.guild.id,d);await log(message.guild,'🔒 PII redacted',`${message.author} • **Channel:** <#${message.channel.id}>\n**Message ID:** \`${message.id}\`\n**Message:** ${preview(red)}`);}}}catch(e){console.error('[mod] content scan:',e?.message||e);}}
function rateLimited(gid,uid){const key=`${gid}:${uid}`,now=Date.now(),x=userRate.get(key)||[];while(x.length&&now-x[0]>USER_WINDOW)x.shift();if(x.length>=USER_LIMIT){userRate.set(key,x);return true;}x.push(now);userRate.set(key,x);return false;}
async function spamScan(message){const c=cfg(message.guild.id);if(!c.antiSpam||mod(message.member))return;if(rateLimited(message.guild.id,message.author.id))return;const key=`${message.guild.id}:${message.author.id}`,now=Date.now();const x=spam.get(key)||[];x.push(message);while(x.length&&now-x[0].createdTimestamp>FLOOD_WINDOW)x.shift();spam.set(key,x);const mentions=message.mentions.users.size+message.mentions.roles.size+(message.mentions.everyone?5:0);const m=mentionSpam.get(key)||[];m.push({message,n:mentions,time:now});while(m.length&&now-m[0].time>MENTION_WINDOW)m.shift();mentionSpam.set(key,m);const mentionTotal=m.reduce((a,b)=>a+b.n,0);if(mentionTotal>=MENTION_LIMIT){for(const v of m)await v.message.delete().catch(()=>{});mentionSpam.delete(key);const d=dashboard.get(message.guild.id)||{};d.spam=(d.spam||0)+1;dashboard.set(message.guild.id,d);await log(message.guild,'🚨 Mention spam blocked',`${message.author} • **Channel:** <#${message.channel.id}>\n**Mentions removed:** ${mentionTotal}\n**Trigger:** ${MENTION_LIMIT}+ mentions within ${MENTION_WINDOW/1000}s`,0xed4245);return;}if(x.length>=FLOOD_LIMIT){const targets=x.slice(-30);let deleted=0;for(const m of targets)if(await m.delete().then(()=>true).catch(()=>false))deleted++;spam.delete(key);const d=dashboard.get(message.guild.id)||{};d.spam=(d.spam||0)+1;dashboard.set(message.guild.id,d);await log(message.guild,'🌊 Flood blocked',`${message.author} • **Channel:** <#${message.channel.id}>\n**Messages deleted:** ${deleted}\n**Trigger:** ${FLOOD_LIMIT}+ messages within ${FLOOD_WINDOW/1000}s`,0xed4245);}}
function panelEmbed(gid){const c=cfg(gid),d=dashboard.get(gid)||{};return new EmbedBuilder().setTitle('🛡️ Moderation dashboard').setColor(0x5865f2).addFields({name:'Prefix',value:`\`${c.prefix}\``,inline:true},{name:'NSFW',value:c.nsfwFilter?'🟢 On':'🔴 Off',inline:true},{name:'Gore',value:c.goreFilter?'🟢 On':'🔴 Off',inline:true},{name:'PII',value:c.piiFilter?'🟢 On':'🔴 Off',inline:true},{name:'Anti-spam/flood',value:c.antiSpam?'🟢 On':'🔴 Off',inline:true},{name:'Scans',value:String(d.scans||0),inline:true},{name:'Removed',value:String(d.removed||0),inline:true},{name:'Spam events',value:String(d.spam||0),inline:true},{name:'PII redactions',value:String(d.pii||0),inline:true});}
function install(client){if(client.__advancedModerationInstalled)return;client.__advancedModerationInstalled=true;client.on('messageCreate',m=>{if(!m.inGuild()||m.author.bot)return;const d=dashboard.get(m.guild.id)||{};d.scans=(d.scans||0)+1;dashboard.set(m.guild.id,d);spamScan(m);enqueue(()=>contentScan(m));});client.on('messageUpdate',async(oldM,newM)=>{if(!newM.inGuild()||newM.author?.bot)return;await newM.fetch().catch(()=>{});enqueue(()=>contentScan(newM));});client.on('ready',async()=>{setTimeout(async()=>{try{const existing=await client.application.commands.fetch();const extras=[new SlashCommandBuilder().setName('modpanel').setDescription('Open the moderation dashboard'),new SlashCommandBuilder().setName('modstats').setDescription('Show moderation statistics'),new SlashCommandBuilder().setName('prefix').setDescription('Change the server prefix').addStringOption(o=>o.setName('value').setDescription('1-3 characters').setRequired(true))];for(const command of extras){const json=command.toJSON();if(!existing.some(x=>x.name===json.name))await client.application.commands.create(json);}}catch(e){console.error('[mod] dashboard command registration:',e.message);}},1500);});client.on('interactionCreate',async i=>{if(!i.isChatInputCommand()||!i.inGuild())return;if(i.commandName==='modpanel'||i.commandName==='modstats'){if(!mod(i.member))return i.reply({content:'❌ Moderator permission required.',ephemeral:true});return i.reply({embeds:[panelEmbed(i.guild.id)],ephemeral:true});}if(i.commandName==='prefix'){if(!mod(i.member))return i.reply({content:'❌ Moderator permission required.',ephemeral:true});const p=i.options.getString('value');if(!p||p.length>3||/\s/.test(p)||p.startsWith('/'))return i.reply({content:'❌ Prefix must be 1-3 non-space characters and cannot start with /.',ephemeral:true});cfg(i.guild.id).prefix=p;save();return i.reply(`✅ Prefix changed to \`${p}\`.`);}});}
const OriginalLogin=Client.prototype.login;Client.prototype.login=async function(...args){install(this);return OriginalLogin.apply(this,args);};
